### ISSUE TITLE
Link to pretrained model is broken

### ISSUE THREAD

**Issue by entn-at** [CODEJIN/GST_Tacotron#1]
Hi, 
thanks for the great repo! I noticed that the checkpoint link (https://drive.google.com/open?id=1zhpJt5VM1jpG4NapsDUKGT_BAr_ZEsfM) leads to a "Error 404" page. Would you be able to update the link?
Thanks,
Ewald

**Comment by CODEJIN** [comment]
> Hi,
> thanks for the great repo! I noticed that the checkpoint link (https://drive.google.com/open?id=1zhpJt5VM1jpG4NapsDUKGT_BAr_ZEsfM) leads to a "Error 404" page. Would you be able to update the link?
> Thanks,
> Ewald

Thanks for the feedback!
I deleted the checkpoint while managing the space on the drive. Now I uploaded again.
