### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ShaharDagan** [CODEJIN/GST_Tacotron#2]
Hi,
Is there any chance for a pretrained model(created from the checkpoint) that outputs the Mel Spectrogram from text(without wav)?
Because when I tried to load the checkpoint I get the following output:
                                                                        
==================================================================================================
Total params: 506,720
Trainable params: 505,824
Non-trainable params: 896
__________________________________________________________________________________________________
Checkpoint 'Checkpoint/S_36000.CHECKPOINT.H5' is loaded.
Inference running...
2020-04-21 10:41:16.278946: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-04-21 10:41:17.310366: W tensorflow/stream_executor/gpu/redzone_allocator.cc:312] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation. This message will be only logged once.
2020-04-21 10:41:17.599566: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_10.dll

And then the program just stops without any warning.
Hope for your help

**Comment by CODEJIN** [comment]
Hi, do you want to get mel spectrogram numpy array by inference? I just modified that. Now Inference function returns mels, stops, spectrograms, and alignments numpy arrays. Please check the Readme.md

**Comment by ShaharDagan** [comment]
Hi Thanks for your quick respond, The problem I facing is that the algorithm doesn't output the WAV file in the folder and stop without any reason and message.
I set up the project in Google Colab:
https://colab.research.google.com/drive/1hworMHo8dRgh8NbroeZpFXJ9wCU-qoOU 
Is there any chance you can fix that the model will output the wav file from the text?
I am using your project as reference for my school project so I will be really glad for your help ( :

**Comment by CODEJIN** [comment]
Hi, I checked your Colab and wrote several code lines. However, when I tried to load the checkpoint, I got **'OutOfRangeError: Read less bytes than requested [Op:RestoreV2]'** error message. This might mean the checkpoint files are broken. I re-uploaded the checkpoint to the Colab directly and tested, and it worked. Please see the code I wrote in your colab and replace the checkpoint files in your github.

**Comment by ShaharDagan** [comment]
Thank you so much! really appreciate it! it works!
